import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { SupportedLocales } from "@/locales";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

//-------------------------------------------------------------------------

const montserrat = Montserrat({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//-------------------------------------------------------------------------

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: SupportedLocales }>;
}) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  //   if (!routing.locales.includes(locale as any)) {
  //     notFound();
  //   }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={montserrat.className}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

{
  /* <html lang="en" suppressHydrationWarning>
  <body className={montserrat.className}>{children}</body>
</html>; */
}
